const USERS = "users/"
const HR = "hr/"

export const GET_ME = USERS + "admin-getme"
export const REFRESH_TOKEN = "refresh_token"
export const REGISTER = "register"
export const LOGIN = USERS + "login/admin"
export const COMPANIES = HR + 'companies'
export const HR_API = 'users'
export const HR_ATTENDED = HR + "attended-users"
export const HR_ABSENTS = HR + "absent-users"
export const ALL_EMPLOYEES = HR + "all-employees"
export const POSITION = USERS + 'roles'
export const ENTRANCE_LOG = 'location/entrance-log'
export const ENTRANCE_WORKING = 'location/working_hourse'
export const OFFICE_DETAILS = HR + 'company-statistics'
export const ROLES_STATISTIC = HR + 'roles-statistics'
export const USER_YEAR_TOTAL = HR + 'user-total-yearly-statistics'
export const USER_YEAR_TOTAL_MONTH = HR + 'user-yearly-statistics'
export const USER_YEAR_TOTAL_MONTH_DAYS = HR + 'user-monthly-statistics'
export const USER_YEAR_TOTAL_MONTH_DAYS_ONE = HR + 'user-daily-statistics'
export const USER_STATISTIC = HR + 'user-statistics-by-role'
export const EXCUSE = HR + 'excuse'
export const ASSIGN_COMPANIES = USERS + 'assign_companies_to_user'